/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const RecommendedWalk = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'distance' : IDL.Float64,
  'isFavourite' : IDL.Bool,
  'location' : Location,
});
export const Customization = IDL.Record({
  'fontSize' : IDL.Nat,
  'backgroundMusic' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Goal = IDL.Record({
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'progress' : IDL.Int,
  'target' : IDL.Int,
});
export const Theme = IDL.Record({
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'accentColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const WalkType = IDL.Variant({
  'Recommended' : IDL.Null,
  'Tracked' : IDL.Null,
});
export const Time = IDL.Int;
export const WalkRating = IDL.Record({
  'walkType' : WalkType,
  'rating' : IDL.Nat,
  'completionTimestamp' : Time,
});
export const WalkSession = IDL.Record({
  'durationInSeconds' : IDL.Nat,
  'distanceInMeters' : IDL.Float64,
  'steps' : IDL.Nat,
  'rating' : IDL.Opt(WalkRating),
  'caloriesBurned' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'addRecommendedWalk' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Location],
      [],
      [],
    ),
  'filterWalksByLocation' : IDL.Func(
      [IDL.Text, Location, IDL.Float64],
      [IDL.Vec(RecommendedWalk)],
      ['query'],
    ),
  'getCustomizations' : IDL.Func([IDL.Text], [Customization], ['query']),
  'getDailyTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getExercisesByCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getGoals' : IDL.Func([IDL.Text], [IDL.Vec(Goal)], ['query']),
  'getRecommendedWalks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RecommendedWalk)],
      ['query'],
    ),
  'getTheme' : IDL.Func([IDL.Text], [Theme], ['query']),
  'getTotalCalories' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTotalSteps' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserWalkHistory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getWalks' : IDL.Func([IDL.Text], [IDL.Vec(WalkSession)], ['query']),
  'markWalkCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'markWalkFavourite' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setCustomizations' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'setTaskCompleted' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'trackWalk' : IDL.Func([IDL.Text, WalkSession], [], []),
  'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const RecommendedWalk = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'distance' : IDL.Float64,
    'isFavourite' : IDL.Bool,
    'location' : Location,
  });
  const Customization = IDL.Record({
    'fontSize' : IDL.Nat,
    'backgroundMusic' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Goal = IDL.Record({
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'progress' : IDL.Int,
    'target' : IDL.Int,
  });
  const Theme = IDL.Record({
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'accentColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const WalkType = IDL.Variant({
    'Recommended' : IDL.Null,
    'Tracked' : IDL.Null,
  });
  const Time = IDL.Int;
  const WalkRating = IDL.Record({
    'walkType' : WalkType,
    'rating' : IDL.Nat,
    'completionTimestamp' : Time,
  });
  const WalkSession = IDL.Record({
    'durationInSeconds' : IDL.Nat,
    'distanceInMeters' : IDL.Float64,
    'steps' : IDL.Nat,
    'rating' : IDL.Opt(WalkRating),
    'caloriesBurned' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'addRecommendedWalk' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Location],
        [],
        [],
      ),
    'filterWalksByLocation' : IDL.Func(
        [IDL.Text, Location, IDL.Float64],
        [IDL.Vec(RecommendedWalk)],
        ['query'],
      ),
    'getCustomizations' : IDL.Func([IDL.Text], [Customization], ['query']),
    'getDailyTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getExercisesByCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getGoals' : IDL.Func([IDL.Text], [IDL.Vec(Goal)], ['query']),
    'getRecommendedWalks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RecommendedWalk)],
        ['query'],
      ),
    'getTheme' : IDL.Func([IDL.Text], [Theme], ['query']),
    'getTotalCalories' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTotalSteps' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserWalkHistory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getWalks' : IDL.Func([IDL.Text], [IDL.Vec(WalkSession)], ['query']),
    'markWalkCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'markWalkFavourite' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setCustomizations' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'setTaskCompleted' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'trackWalk' : IDL.Func([IDL.Text, WalkSession], [], []),
    'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };