/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customization {
  'fontSize' : bigint,
  'backgroundMusic' : string,
}
export interface Exercise {
  'name' : string,
  'description' : string,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export interface Goal {
  'completed' : boolean,
  'description' : string,
  'progress' : bigint,
  'target' : bigint,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export interface RecommendedWalk {
  'id' : bigint,
  'isCompleted' : boolean,
  'name' : string,
  'description' : string,
  'distance' : number,
  'isFavourite' : boolean,
  'location' : Location,
}
export interface Task {
  'id' : bigint,
  'completed' : boolean,
  'description' : string,
  'category' : string,
}
export interface Theme {
  'primaryColor' : string,
  'name' : string,
  'accentColor' : string,
  'secondaryColor' : string,
}
export type Time = bigint;
export interface WalkRating {
  'walkType' : WalkType,
  'rating' : bigint,
  'completionTimestamp' : Time,
}
export interface WalkSession {
  'durationInSeconds' : bigint,
  'distanceInMeters' : number,
  'steps' : bigint,
  'rating' : [] | [WalkRating],
  'caloriesBurned' : bigint,
}
export type WalkType = { 'Recommended' : null } |
  { 'Tracked' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addExercise' : ActorMethod<[string, string, string, string], undefined>,
  'addGoal' : ActorMethod<[string, string, bigint], undefined>,
  'addRecommendedWalk' : ActorMethod<
    [string, string, string, number, Location],
    undefined
  >,
  'filterWalksByLocation' : ActorMethod<
    [string, Location, number],
    Array<RecommendedWalk>
  >,
  'getCustomizations' : ActorMethod<[string], Customization>,
  'getDailyTasks' : ActorMethod<[string], Array<Task>>,
  'getExercisesByCategory' : ActorMethod<[string, string], Array<Exercise>>,
  'getGoals' : ActorMethod<[string], Array<Goal>>,
  'getRecommendedWalks' : ActorMethod<[string], Array<RecommendedWalk>>,
  'getTheme' : ActorMethod<[string], Theme>,
  'getTotalCalories' : ActorMethod<[string], bigint>,
  'getTotalSteps' : ActorMethod<[string], bigint>,
  'getUserWalkHistory' : ActorMethod<[string], Array<bigint>>,
  'getWalks' : ActorMethod<[string], Array<WalkSession>>,
  'markWalkCompleted' : ActorMethod<[string, bigint], undefined>,
  'markWalkFavourite' : ActorMethod<[string, bigint], undefined>,
  'setCustomizations' : ActorMethod<[string, bigint, string], undefined>,
  'setTaskCompleted' : ActorMethod<[string, bigint], boolean>,
  'setTheme' : ActorMethod<[string, string], undefined>,
  'trackWalk' : ActorMethod<[string, WalkSession], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];