/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface Exercise {
    name: string;
    description: string;
    category: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Customization {
    fontSize: bigint;
    backgroundMusic: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: bigint;
    completed: boolean;
    description: string;
    category: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RecommendedWalk {
    id: bigint;
    isCompleted: boolean;
    name: string;
    description: string;
    distance: number;
    isFavourite: boolean;
    location: Location;
}
export interface Theme {
    primaryColor: string;
    name: string;
    accentColor: string;
    secondaryColor: string;
}
export interface WalkRating {
    walkType: WalkType;
    rating: bigint;
    completionTimestamp: Time;
}
export interface WalkSession {
    durationInSeconds: bigint;
    distanceInMeters: number;
    steps: bigint;
    rating?: WalkRating;
    caloriesBurned: bigint;
}
export interface Goal {
    completed: boolean;
    description: string;
    progress: bigint;
    target: bigint;
}
export enum WalkType {
    Recommended = "Recommended",
    Tracked = "Tracked"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addExercise(_profileId: string, name: string, description: string, category: string): Promise<void>;
    addGoal(profileId: string, description: string, target: bigint): Promise<void>;
    addRecommendedWalk(_profileId: string, name: string, description: string, distance: number, location: Location): Promise<void>;
    filterWalksByLocation(_profileId: string, userLocation: Location, maxDistance: number): Promise<Array<RecommendedWalk>>;
    getCustomizations(profileId: string): Promise<Customization>;
    getDailyTasks(profileId: string): Promise<Array<Task>>;
    getExercisesByCategory(_profileId: string, category: string): Promise<Array<Exercise>>;
    getGoals(profileId: string): Promise<Array<Goal>>;
    getRecommendedWalks(_profileId: string): Promise<Array<RecommendedWalk>>;
    getTheme(profileId: string): Promise<Theme>;
    getTotalCalories(profileId: string): Promise<bigint>;
    getTotalSteps(profileId: string): Promise<bigint>;
    getUserWalkHistory(profileId: string): Promise<Array<bigint>>;
    getWalks(profileId: string): Promise<Array<WalkSession>>;
    markWalkCompleted(profileId: string, walkId: bigint): Promise<void>;
    markWalkFavourite(_profileId: string, walkId: bigint): Promise<void>;
    setCustomizations(profileId: string, fontSize: bigint, backgroundMusic: string): Promise<void>;
    setTaskCompleted(profileId: string, taskId: bigint): Promise<boolean>;
    setTheme(profileId: string, themeName: string): Promise<void>;
    trackWalk(profileId: string, session: WalkSession): Promise<void>;
    uploadPhoto(_photo: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Time as _Time, WalkRating as _WalkRating, WalkSession as _WalkSession, WalkType as _WalkType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addExercise(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addGoal(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async addRecommendedWalk(arg0: string, arg1: string, arg2: string, arg3: number, arg4: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecommendedWalk(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecommendedWalk(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async filterWalksByLocation(arg0: string, arg1: Location, arg2: number): Promise<Array<RecommendedWalk>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterWalksByLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterWalksByLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async getCustomizations(arg0: string): Promise<Customization> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomizations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomizations(arg0);
            return result;
        }
    }
    async getDailyTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTasks(arg0);
            return result;
        }
    }
    async getExercisesByCategory(arg0: string, arg1: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByCategory(arg0, arg1);
            return result;
        }
    }
    async getGoals(arg0: string): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals(arg0);
            return result;
        }
    }
    async getRecommendedWalks(arg0: string): Promise<Array<RecommendedWalk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedWalks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedWalks(arg0);
            return result;
        }
    }
    async getTheme(arg0: string): Promise<Theme> {
        if (this.processError) {
            try {
                const result = await this.actor.getTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTheme(arg0);
            return result;
        }
    }
    async getTotalCalories(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCalories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCalories(arg0);
            return result;
        }
    }
    async getTotalSteps(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSteps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSteps(arg0);
            return result;
        }
    }
    async getUserWalkHistory(arg0: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWalkHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWalkHistory(arg0);
            return result;
        }
    }
    async getWalks(arg0: string): Promise<Array<WalkSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalks(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalks(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async markWalkCompleted(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWalkCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWalkCompleted(arg0, arg1);
            return result;
        }
    }
    async markWalkFavourite(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWalkFavourite(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWalkFavourite(arg0, arg1);
            return result;
        }
    }
    async setCustomizations(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCustomizations(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCustomizations(arg0, arg1, arg2);
            return result;
        }
    }
    async setTaskCompleted(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskCompleted(arg0, arg1);
            return result;
        }
    }
    async setTheme(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTheme(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTheme(arg0, arg1);
            return result;
        }
    }
    async trackWalk(arg0: string, arg1: WalkSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackWalk(arg0, to_candid_WalkSession_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackWalk(arg0, to_candid_WalkSession_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadPhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_WalkRating_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalkRating): WalkRating {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WalkSession_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalkSession): WalkSession {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WalkType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalkType): WalkType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalkRating]): WalkRating | null {
    return value.length === 0 ? null : from_candid_WalkRating_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationInSeconds: bigint;
    distanceInMeters: number;
    steps: bigint;
    rating: [] | [_WalkRating];
    caloriesBurned: bigint;
}): {
    durationInSeconds: bigint;
    distanceInMeters: number;
    steps: bigint;
    rating?: WalkRating;
    caloriesBurned: bigint;
} {
    return {
        durationInSeconds: value.durationInSeconds,
        distanceInMeters: value.distanceInMeters,
        steps: value.steps,
        rating: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.rating)),
        caloriesBurned: value.caloriesBurned
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walkType: _WalkType;
    rating: bigint;
    completionTimestamp: _Time;
}): {
    walkType: WalkType;
    rating: bigint;
    completionTimestamp: Time;
} {
    return {
        walkType: from_candid_WalkType_n14(_uploadFile, _downloadFile, value.walkType),
        rating: value.rating,
        completionTimestamp: value.completionTimestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Recommended: null;
} | {
    Tracked: null;
}): WalkType {
    return "Recommended" in value ? WalkType.Recommended : "Tracked" in value ? WalkType.Tracked : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalkSession>): Array<WalkSession> {
    return value.map((x)=>from_candid_WalkSession_n9(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_WalkRating_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalkRating): _WalkRating {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_WalkSession_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalkSession): _WalkSession {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_WalkType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalkType): _WalkType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationInSeconds: bigint;
    distanceInMeters: number;
    steps: bigint;
    rating?: WalkRating;
    caloriesBurned: bigint;
}): {
    durationInSeconds: bigint;
    distanceInMeters: number;
    steps: bigint;
    rating: [] | [_WalkRating];
    caloriesBurned: bigint;
} {
    return {
        durationInSeconds: value.durationInSeconds,
        distanceInMeters: value.distanceInMeters,
        steps: value.steps,
        rating: value.rating ? candid_some(to_candid_WalkRating_n18(_uploadFile, _downloadFile, value.rating)) : candid_none(),
        caloriesBurned: value.caloriesBurned
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walkType: WalkType;
    rating: bigint;
    completionTimestamp: Time;
}): {
    walkType: _WalkType;
    rating: bigint;
    completionTimestamp: _Time;
} {
    return {
        walkType: to_candid_WalkType_n20(_uploadFile, _downloadFile, value.walkType),
        rating: value.rating,
        completionTimestamp: value.completionTimestamp
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalkType): {
    Recommended: null;
} | {
    Tracked: null;
} {
    return value == WalkType.Recommended ? {
        Recommended: null
    } : value == WalkType.Tracked ? {
        Tracked: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
